### ISSUE TITLE
Gallery Lightbox Formatting

### ISSUE THREAD

**Issue by jlamoreaux** [jlamoreaux/one-more-lamore#1]
# Expected Behavior
When viewing images from a gallery, the lightbox should be showing one image, with the option to "scroll" left and right by clicking the arrow options.

# Current Behavior
All images appear at once on the page. User can scroll vertically to view images.

# TODO
- [x] Black background should cover the screen
- [x] Next & Previous arrows should allow users to view other images
- [x] Only one image should appear at a time

**Comment by jlamoreaux** [comment]
Resolved! 🏎️
